# see https://docs.streamlit.io/develop/api-reference/configuration/config.toml

[global]

[logger]
messageFormat = "%(asctime)s\t%(levelname)s\t%(name)s\t%(message)s"
level = "info"

[client]
showErrorDetails = "full"

[runner]

[server]
address = "127.0.0.1"        # localhost only for local dev
baseUrlPath = "/mindchat"
fileWatcherType = "watchdog"
maxUploadSize = 1            # MB
port = 8504

[browser]
gatherUsageStats = false

[mapbox]

[theme]
base = "light"

[secrets]
