login_password = "xxx"

# from https://platform.openai.com/settings/organization/api-keys
openai_api_key = "xxx"

mistral_api_key = "xxx"

# https://aistudio.google.com/app/api-keys
google_api_key = ""
